// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9HBfa97vJB_HM6ql5o_HukegTczqBqdU',
    appId: '1:921920018913:web:e715e089656c8c8130daa0',
    messagingSenderId: '921920018913',
    projectId: 'softec-project-23983',
    authDomain: 'softec-project-23983.firebaseapp.com',
    storageBucket: 'softec-project-23983.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqc4xFLdNOqYXhCm61-nTP2ppksb_X4kM',
    appId: '1:921920018913:android:9e1432b96b1ac1cf30daa0',
    messagingSenderId: '921920018913',
    projectId: 'softec-project-23983',
    storageBucket: 'softec-project-23983.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBttuAio_2McrMKvPlQsl1DfPjgC85CXdo',
    appId: '1:921920018913:ios:d14244e764529dd130daa0',
    messagingSenderId: '921920018913',
    projectId: 'softec-project-23983',
    storageBucket: 'softec-project-23983.firebasestorage.app',
    iosBundleId: 'com.example.softecProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBttuAio_2McrMKvPlQsl1DfPjgC85CXdo',
    appId: '1:921920018913:ios:d14244e764529dd130daa0',
    messagingSenderId: '921920018913',
    projectId: 'softec-project-23983',
    storageBucket: 'softec-project-23983.firebasestorage.app',
    iosBundleId: 'com.example.softecProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9HBfa97vJB_HM6ql5o_HukegTczqBqdU',
    appId: '1:921920018913:web:427c060bc604438f30daa0',
    messagingSenderId: '921920018913',
    projectId: 'softec-project-23983',
    authDomain: 'softec-project-23983.firebaseapp.com',
    storageBucket: 'softec-project-23983.firebasestorage.app',
  );
}
